steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    id: clone
    args:
      - clone
      - https://github.com/dannykil/Vertex_AI.git

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/container-dev-web/web:$COMMIT_SHA',
        '.',
      ]

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/container-dev-web/web:$COMMIT_SHA',
      ]

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dev-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/container-dev-web/web:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
images:
  - 'gcr.io/$PROJECT_ID/container-dev-web/web:$COMMIT_SHA'
# steps:
# # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/dev-web:$COMMIT_SHA', '.']
# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/dev-web:$COMMIT_SHA']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args:
#   - 'run'
#   - 'deploy'
#   - 'dev-web'
#   - '--image'
#   - 'gcr.io/$PROJECT_ID/dev-web:$COMMIT_SHA'
#   - '--region'
#   - 'SERVICE_REGION'
# images:
# - 'gcr.io/$PROJECT_ID/dev-web:$COMMIT_SHA'
