steps:
  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    id: clone
    args:
      - clone
      - https://github.com/dannykil/Vertex_AI.git

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/container-dev-web/web:$COMMIT_SHA',
        '.',
      ]

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/${PROJECT_ID}/container-dev-web/web:$COMMIT_SHA',
      ]

  # Entrypoint, timeout and environment variables
  # docker pull us-central1-docker.pkg.dev/gen-lang-client-0274842719/container-dev-web/web:305d6893e21a696ab272abe09a2a9466fb5ced25
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dev-web'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/container-dev-web/web:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      # - 'gcr.io/$PROJECT_ID/container-dev-web/web:$COMMIT_SHA'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/container-dev-web/web:$COMMIT_SHA'
  # - 'gcr.io/$PROJECT_ID/container-dev-web/web:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
