steps:
  # Clone the repository
  # https://github.com/dannykil/Vertex_AI.git
  - name: "gcr.io/cloud-builders/git"
    args:
      - clone
      - https://github.com/dannykil/Vertex_AI.git
      # - --recurse-submodules
      # - git@github.com:dannykil/Vertex_AI.git
    # volumes:
    #   - name: ssh
    #     path: /root/.ssh

  # Docker Build
  # us-central1-docker.pkg.dev/gen-lang-client-0274842719/container-dev-web/web@sha256:01ee1939029070a16dacb7836b31d6e9ccd3eddbcf2a322ad7169b27e70d4c6f
  - name: "gcr.io/cloud-builders/docker"
    # - name: "us-central1-docker.pkg.dev/gen-lang-client-0274842719/container-dev-web/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/container-dev-web/web:tag1",
        ".",
      ]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    # - name: "us-central1-docker.pkg.dev/gen-lang-client-0274842719/container-dev-web/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/${PROJECT_ID}/container-dev-web/web:tag1",
      ]

options:
  logging: CLOUD_LOGGING_ONLY

  # Entrypoint, timeout and environment variables
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   timeout: 240s
  #   args: ['compute', 'instances',
  #          'create-with-container', 'my-vm-name',
  #          '--container-image',
  #          'us-central1-docker.pkg.dev/${PROJECT_ID}/container-dev-web/web:tag1']
  #   env:
  #     - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  #     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
